*Open the file containing the historical metric values we would like to validate.
GET FILE = '/usr/spss/userdata/Albrecht/PPC Geo/Sales and Transaction History by Account.sav'.
CACHE.
EXE.

DATASET NAME ACCTS.
DATASET ACTIVATE ACCTS.

/*LOOK AT THE TOTAL AND DAILY SALES/TRANS TRENDS FOR THE TEST AND CONTROL MARKETS*/.

*Select only accounts with sales history and in the DMAs we have selected for test and control markets.
DATASET COPY SA.
DATASET ACTIVATE SA.

SELECT IF(Has_Sales >= 1 AND ANY(DMA,'ERIE','PEORIA - BLOOMINGTON','BIRMINGHAM (ANN & TUSC)','KNOXVILLE','FARGO - VALLEY CITY','LAS VEGAS',
                                                                  'AUGUSTA - AIKEN','SPRINGFIELD - HOLYOKE','FRESNO - VISALIA','LEXINGTON','JACKSON, MS','MADISON',
                                                                  'BLUEFIELD - BECKLEY - OAK HILL','FT- SMITH - FAY - SPRNGDL - RG','RICHMOND - PETERSBURG', 
                                                                  'GREENSBORO - H- POINT - W- SAL','LA CROSSE - EAU CLAIRE','TUCSON (SIERRA VISTA)',
                                                                  'DAVENPORT - R- ISLAND - MOLINE','YOUNGSTOWN','LANSING','GREENVLL - SPART - ASHEVLL - A','OMAHA','SIOUX CITY')).
EXE.

FREQ DMA.

*Daily sales.
DATASET DECLARE AGG_DS.

AGGREGATE
  /OUTFILE='AGG_DS'
  /BREAK=DMA
  /ADS1=SUM(ADS1) 
  /ADS2=SUM(ADS2) 
  /ADS3=SUM(ADS3) 
  /ADS4=SUM(ADS4) 
  /ADS5=SUM(ADS5) 
  /ADS6=SUM(ADS6) 
  /ADS7=SUM(ADS7) 
  /ADS8=SUM(ADS8) 
  /ADS9=SUM(ADS9) 
  /ADS10=SUM(ADS10) 
  /ADS11=SUM(ADS11) 
  /ADS12=SUM(ADS12) 
  /ADS13=SUM(ADS13) 
  /ADS14=SUM(ADS14) 
  /ADS15=SUM(ADS15) 
  /ADS16=SUM(ADS16) 
  /ADS17=SUM(ADS17) 
  /ADS18=SUM(ADS18) 
  /ADS19=SUM(ADS19) 
  /ADS20=SUM(ADS20) 
  /ADS21=SUM(ADS21) 
  /ADS22=SUM(ADS22) 
  /ADS23=SUM(ADS23) 
  /ADS24=SUM(ADS24) 
  /ADS25=SUM(ADS25) 
  /ADS26=SUM(ADS26) 
  /ADS27=SUM(ADS27) 
  /ADS28=SUM(ADS28) 
  /ADS29=SUM(ADS29) 
  /ADS30=SUM(ADS30) 
  /ADS31=SUM(ADS31) 
  /ADS32=SUM(ADS32) 
  /ADS33=SUM(ADS33) 
  /ADS34=SUM(ADS34) 
  /ADS35=SUM(ADS35) 
  /ADS36=SUM(ADS36) 
  /ADS37=SUM(ADS37) 
  /ADS38=SUM(ADS38) 
  /ADS39=SUM(ADS39) 
  /ADS40=SUM(ADS40) 
  /ADS41=SUM(ADS41) 
  /ADS42=SUM(ADS42) 
  /ADS43=SUM(ADS43) 
  /ADS44=SUM(ADS44) 
  /ADS45=SUM(ADS45) 
  /ADS46=SUM(ADS46) 
  /ADS47=SUM(ADS47) 
  /ADS48=SUM(ADS48) 
  /ADS49=SUM(ADS49) 
  /ADS50=SUM(ADS50) 
  /ADS51=SUM(ADS51) 
  /ADS52=SUM(ADS52) 
  /ADS53=SUM(ADS53) 
  /ADS54=SUM(ADS54) 
  /ADS55=SUM(ADS55) 
  /ADS56=SUM(ADS56) 
  /ADS57=SUM(ADS57) 
  /ADS58=SUM(ADS58) 
  /ADS59=SUM(ADS59) 
  /ADS60=SUM(ADS60)
  /ACCTS=N.

DATASET ACTIVATE AGG_DS.

DATASET ACTIVATE SA.

COMPUTE Group = 0.
IF(ANY(DMA,'ERIE','PEORIA - BLOOMINGTON','BIRMINGHAM (ANN & TUSC)','KNOXVILLE','FARGO - VALLEY CITY','LAS VEGAS')) Group = 1.
IF(ANY(DMA, 'AUGUSTA - AIKEN','SPRINGFIELD - HOLYOKE','FRESNO - VISALIA','LEXINGTON','JACKSON, MS','MADISON')) Group = 2.
IF(ANY(DMA,'BLUEFIELD - BECKLEY - OAK HILL','FT- SMITH - FAY - SPRNGDL - RG','RICHMOND - PETERSBURG', 
                    'GREENSBORO - H- POINT - W- SAL','LA CROSSE - EAU CLAIRE','TUCSON (SIERRA VISTA)')) Group = 3.
IF(ANY(DMA, 'DAVENPORT - R- ISLAND - MOLINE','YOUNGSTOWN','LANSING','GREENVLL - SPART - ASHEVLL - A','OMAHA','SIOUX CITY')) Group = 4.
FORMATS Group(F1.0).
EXE.

FREQ Group.

***CORRECT OUTLIER IN DAILY SALES FOR ACCOUNT 864197819 IN SEPTEMBER OF 2012***.
IF(account = 864197819) ADS19 = ADS18.
EXE.

*Daily sales.
DATASET DECLARE AGG_DS2.

AGGREGATE
  /OUTFILE='AGG_DS2'
  /BREAK=Group
  /ADS1=SUM(ADS1) 
  /ADS2=SUM(ADS2) 
  /ADS3=SUM(ADS3) 
  /ADS4=SUM(ADS4) 
  /ADS5=SUM(ADS5) 
  /ADS6=SUM(ADS6) 
  /ADS7=SUM(ADS7) 
  /ADS8=SUM(ADS8) 
  /ADS9=SUM(ADS9) 
  /ADS10=SUM(ADS10) 
  /ADS11=SUM(ADS11) 
  /ADS12=SUM(ADS12) 
  /ADS13=SUM(ADS13) 
  /ADS14=SUM(ADS14) 
  /ADS15=SUM(ADS15) 
  /ADS16=SUM(ADS16) 
  /ADS17=SUM(ADS17) 
  /ADS18=SUM(ADS18) 
  /ADS19=SUM(ADS19) 
  /ADS20=SUM(ADS20) 
  /ADS21=SUM(ADS21) 
  /ADS22=SUM(ADS22) 
  /ADS23=SUM(ADS23) 
  /ADS24=SUM(ADS24) 
  /ADS25=SUM(ADS25) 
  /ADS26=SUM(ADS26) 
  /ADS27=SUM(ADS27) 
  /ADS28=SUM(ADS28) 
  /ADS29=SUM(ADS29) 
  /ADS30=SUM(ADS30) 
  /ADS31=SUM(ADS31) 
  /ADS32=SUM(ADS32) 
  /ADS33=SUM(ADS33) 
  /ADS34=SUM(ADS34) 
  /ADS35=SUM(ADS35) 
  /ADS36=SUM(ADS36) 
  /ADS37=SUM(ADS37) 
  /ADS38=SUM(ADS38) 
  /ADS39=SUM(ADS39) 
  /ADS40=SUM(ADS40) 
  /ADS41=SUM(ADS41) 
  /ADS42=SUM(ADS42) 
  /ADS43=SUM(ADS43) 
  /ADS44=SUM(ADS44) 
  /ADS45=SUM(ADS45) 
  /ADS46=SUM(ADS46) 
  /ADS47=SUM(ADS47) 
  /ADS48=SUM(ADS48) 
  /ADS49=SUM(ADS49) 
  /ADS50=SUM(ADS50) 
  /ADS51=SUM(ADS51) 
  /ADS52=SUM(ADS52) 
  /ADS53=SUM(ADS53) 
  /ADS54=SUM(ADS54) 
  /ADS55=SUM(ADS55) 
  /ADS56=SUM(ADS56) 
  /ADS57=SUM(ADS57) 
  /ADS58=SUM(ADS58) 
  /ADS59=SUM(ADS59) 
  /ADS60=SUM(ADS60)
  /ACCTS=N.

DATASET ACTIVATE AGG_DS2.

COMPUTE ADS61 = 0.
COMPUTE ADS62 = 0.
COMPUTE ADS63 = 0.
COMPUTE ADS64 = 0.
COMPUTE ADS65 = 0.
COMPUTE ADS66 = 0.
COMPUTE ADS67 = 0.
COMPUTE ADS68 = 0.
COMPUTE ADS69 = 0.
COMPUTE ADS70 = 0.
COMPUTE ADS71 = 0.
COMPUTE ADS72 = 0.
EXE.

FLIP VARIABLES=ADS1 ADS2 ADS3 ADS4 ADS5 ADS6 ADS7 ADS8 ADS9 ADS10 ADS11 ADS12 ADS13 ADS14 ADS15 
    ADS16 ADS17 ADS18 ADS19 ADS20 ADS21 ADS22 ADS23 ADS24 ADS25 ADS26 ADS27 ADS28 ADS29 ADS30 ADS31 
    ADS32 ADS33 ADS34 ADS35 ADS36 ADS37 ADS38 ADS39 ADS40 ADS41 ADS42 ADS43 ADS44 ADS45 ADS46 ADS47 
    ADS48 ADS49 ADS50 ADS51 ADS52 ADS53 ADS54 ADS55 ADS56 ADS57 ADS58 ADS59 ADS60 ADS61 ADS62 ADS63
    ADS64 ADS65 ADS66 ADS67 ADS68 ADS69 ADS70 ADS71 ADS72
  /NEWNAMES=Group.

DATASET NAME DS_TS.
DATASET ACTIVATE DS_TS.

RENAME VARIABLES K_1 = Group1 K_2 = Group2 K_3 = Group3 K_4 = Group4.

DATE M 3 12 Y 2011.

*Group 1 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group1 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 2 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group2 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 3 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group3 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 4 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group4 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Gcom Daily Sales.
DATASET CLOSE AGG_DS2.
DATASET CLOSE DS_TS.
DATASET ACTIVATE SA.

DATASET DECLARE AGG_GCDS.

AGGREGATE
  /OUTFILE='AGG_GCDS'
  /BREAK=DMA
  /ADGCS1=SUM(ADGCS1) 
  /ADGCS2=SUM(ADGCS2) 
  /ADGCS3=SUM(ADGCS3) 
  /ADGCS4=SUM(ADGCS4) 
  /ADGCS5=SUM(ADGCS5) 
  /ADGCS6=SUM(ADGCS6) 
  /ADGCS7=SUM(ADGCS7) 
  /ADGCS8=SUM(ADGCS8) 
  /ADGCS9=SUM(ADGCS9) 
  /ADGCS10=SUM(ADGCS10) 
  /ADGCS11=SUM(ADGCS11) 
  /ADGCS12=SUM(ADGCS12) 
  /ADGCS13=SUM(ADGCS13) 
  /ADGCS14=SUM(ADGCS14) 
  /ADGCS15=SUM(ADGCS15) 
  /ADGCS16=SUM(ADGCS16) 
  /ADGCS17=SUM(ADGCS17) 
  /ADGCS18=SUM(ADGCS18) 
  /ADGCS19=SUM(ADGCS19) 
  /ADGCS20=SUM(ADGCS20) 
  /ADGCS21=SUM(ADGCS21) 
  /ADGCS22=SUM(ADGCS22) 
  /ADGCS23=SUM(ADGCS23) 
  /ADGCS24=SUM(ADGCS24) 
  /ADGCS25=SUM(ADGCS25) 
  /ADGCS26=SUM(ADGCS26) 
  /ADGCS27=SUM(ADGCS27) 
  /ADGCS28=SUM(ADGCS28) 
  /ADGCS29=SUM(ADGCS29) 
  /ADGCS30=SUM(ADGCS30) 
  /ADGCS31=SUM(ADGCS31) 
  /ADGCS32=SUM(ADGCS32) 
  /ADGCS33=SUM(ADGCS33) 
  /ADGCS34=SUM(ADGCS34) 
  /ADGCS35=SUM(ADGCS35) 
  /ADGCS36=SUM(ADGCS36) 
  /ADGCS37=SUM(ADGCS37) 
  /ADGCS38=SUM(ADGCS38) 
  /ADGCS39=SUM(ADGCS39) 
  /ADGCS40=SUM(ADGCS40) 
  /ADGCS41=SUM(ADGCS41) 
  /ADGCS42=SUM(ADGCS42) 
  /ADGCS43=SUM(ADGCS43) 
  /ADGCS44=SUM(ADGCS44) 
  /ADGCS45=SUM(ADGCS45) 
  /ADGCS46=SUM(ADGCS46) 
  /ADGCS47=SUM(ADGCS47) 
  /ADGCS48=SUM(ADGCS48) 
  /ADGCS49=SUM(ADGCS49) 
  /ADGCS50=SUM(ADGCS50) 
  /ADGCS51=SUM(ADGCS51) 
  /ADGCS52=SUM(ADGCS52) 
  /ADGCS53=SUM(ADGCS53) 
  /ADGCS54=SUM(ADGCS54) 
  /ADGCS55=SUM(ADGCS55) 
  /ADGCS56=SUM(ADGCS56) 
  /ADGCS57=SUM(ADGCS57) 
  /ADGCS58=SUM(ADGCS58) 
  /ADGCS59=SUM(ADGCS59) 
  /ADGCS60=SUM(ADGCS60)
  /ACCTS=N.

DATASET ACTIVATE AGG_GCDS.

*Gcom Daily sales.
DATASET ACTIVATE SA.

DATASET DECLARE AGG_GCDS2.

AGGREGATE
  /OUTFILE='AGG_GCDS2'
  /BREAK=Group
  /ADGCS1=SUM(ADGCS1) 
  /ADGCS2=SUM(ADGCS2) 
  /ADGCS3=SUM(ADGCS3) 
  /ADGCS4=SUM(ADGCS4) 
  /ADGCS5=SUM(ADGCS5) 
  /ADGCS6=SUM(ADGCS6) 
  /ADGCS7=SUM(ADGCS7) 
  /ADGCS8=SUM(ADGCS8) 
  /ADGCS9=SUM(ADGCS9) 
  /ADGCS10=SUM(ADGCS10) 
  /ADGCS11=SUM(ADGCS11) 
  /ADGCS12=SUM(ADGCS12) 
  /ADGCS13=SUM(ADGCS13) 
  /ADGCS14=SUM(ADGCS14) 
  /ADGCS15=SUM(ADGCS15) 
  /ADGCS16=SUM(ADGCS16) 
  /ADGCS17=SUM(ADGCS17) 
  /ADGCS18=SUM(ADGCS18) 
  /ADGCS19=SUM(ADGCS19) 
  /ADGCS20=SUM(ADGCS20) 
  /ADGCS21=SUM(ADGCS21) 
  /ADGCS22=SUM(ADGCS22) 
  /ADGCS23=SUM(ADGCS23) 
  /ADGCS24=SUM(ADGCS24) 
  /ADGCS25=SUM(ADGCS25) 
  /ADGCS26=SUM(ADGCS26) 
  /ADGCS27=SUM(ADGCS27) 
  /ADGCS28=SUM(ADGCS28) 
  /ADGCS29=SUM(ADGCS29) 
  /ADGCS30=SUM(ADGCS30) 
  /ADGCS31=SUM(ADGCS31) 
  /ADGCS32=SUM(ADGCS32) 
  /ADGCS33=SUM(ADGCS33) 
  /ADGCS34=SUM(ADGCS34) 
  /ADGCS35=SUM(ADGCS35) 
  /ADGCS36=SUM(ADGCS36) 
  /ADGCS37=SUM(ADGCS37) 
  /ADGCS38=SUM(ADGCS38) 
  /ADGCS39=SUM(ADGCS39) 
  /ADGCS40=SUM(ADGCS40) 
  /ADGCS41=SUM(ADGCS41) 
  /ADGCS42=SUM(ADGCS42) 
  /ADGCS43=SUM(ADGCS43) 
  /ADGCS44=SUM(ADGCS44) 
  /ADGCS45=SUM(ADGCS45) 
  /ADGCS46=SUM(ADGCS46) 
  /ADGCS47=SUM(ADGCS47) 
  /ADGCS48=SUM(ADGCS48) 
  /ADGCS49=SUM(ADGCS49) 
  /ADGCS50=SUM(ADGCS50) 
  /ADGCS51=SUM(ADGCS51) 
  /ADGCS52=SUM(ADGCS52) 
  /ADGCS53=SUM(ADGCS53) 
  /ADGCS54=SUM(ADGCS54) 
  /ADGCS55=SUM(ADGCS55) 
  /ADGCS56=SUM(ADGCS56) 
  /ADGCS57=SUM(ADGCS57) 
  /ADGCS58=SUM(ADGCS58) 
  /ADGCS59=SUM(ADGCS59) 
  /ADGCS60=SUM(ADGCS60)
  /ACCTS=N.

DATASET ACTIVATE AGG_GCDS2.

COMPUTE ADGCS61 = 0.
COMPUTE ADGCS62 = 0.
COMPUTE ADGCS63 = 0.
COMPUTE ADGCS64 = 0.
COMPUTE ADGCS65 = 0.
COMPUTE ADGCS66 = 0.
COMPUTE ADGCS67 = 0.
COMPUTE ADGCS68 = 0.
COMPUTE ADGCS69 = 0.
COMPUTE ADGCS70 = 0.
COMPUTE ADGCS71 = 0.
COMPUTE ADGCS72 = 0.
EXE.

FLIP VARIABLES=ADGCS1 ADGCS2 ADGCS3 ADGCS4 ADGCS5 ADGCS6 ADGCS7 ADGCS8 ADGCS9 ADGCS10 ADGCS11 ADGCS12 ADGCS13 ADGCS14 ADGCS15 
    ADGCS16 ADGCS17 ADGCS18 ADGCS19 ADGCS20 ADGCS21 ADGCS22 ADGCS23 ADGCS24 ADGCS25 ADGCS26 ADGCS27 ADGCS28 ADGCS29 ADGCS30 ADGCS31 
    ADGCS32 ADGCS33 ADGCS34 ADGCS35 ADGCS36 ADGCS37 ADGCS38 ADGCS39 ADGCS40 ADGCS41 ADGCS42 ADGCS43 ADGCS44 ADGCS45 ADGCS46 ADGCS47 
    ADGCS48 ADGCS49 ADGCS50 ADGCS51 ADGCS52 ADGCS53 ADGCS54 ADGCS55 ADGCS56 ADGCS57 ADGCS58 ADGCS59 ADGCS60 ADGCS61 ADGCS62 ADGCS63
    ADGCS64 ADGCS65 ADGCS66 ADGCS67 ADGCS68 ADGCS69 ADGCS70 ADGCS71 ADGCS72
  /NEWNAMES=Group.

DATASET NAME DGCS_TS.
DATASET ACTIVATE DGCS_TS.

RENAME VARIABLES K_1 = Group1 K_2 = Group2 K_3 = Group3 K_4 = Group4.

DATE M 3 12 Y 2011.

*Group 1 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group1 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 2 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group2 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 3 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group3 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 4 Forecast.
USE year 2011 month 3 THRU year 2016 month 2.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group4 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

DATASET CLOSE AGG_GCDS2.
DATASET CLOSE DGCS_TS.

*Avg PPC Daily Visits.
GET FILE = '/usr/spss/userdata/Albrecht/PPC Geo/PPC Metrics by All Zipcodes.sav'.
CACHE.
EXE.

DATASET NAME PPC.
DATASET ACTIVATE PPC.

COMPUTE Group = 0.
IF(ANY(DMA,'BLUEFIELD - BECKLEY - OAK HILL','ERIE','GREENVLL - SPART - ASHEVLL - A','LANSING','OMAHA','SIOUX CITY')) Group = 1.
IF(ANY(DMA,'SPRINGFIELD - HOLYOKE','LIMA','BIRMINGHAM (ANN & TUSC)','RICHMOND - PETERSBURG','FARGO - VALLEY CITY','LAS VEGAS')) Group = 2.
IF(ANY(DMA,'COLUMBUS, GA (OPELIKA, AL)','JONESBORO','LEXINGTON','FRESNO - VISALIA','JACKSON, MS','MADISON')) Group = 3.
IF(ANY(DMA,'DAVENPORT - R- ISLAND - MOLINE','YOUNGSTOWN','GREENSBORO - H- POINT - W- SAL','KNOXVILLE',
                     'LA CROSSE - EAU CLAIRE','TUCSON (SIERRA VISTA)')) Group = 4.
VALUE LABELS Group 1 'Control' 2 'Zero Spend' 3 'Spend Up' 4 'Spend Down'.
FORMATS Group(F1.0).
EXE.

DATASET DECLARE PPC_VIS.

AGGREGATE
  /OUTFILE='PPC_VIS'
  /BREAK=Group
  /Visits_201504=SUM(Visits_201504) 
  /Visits_201505=SUM(Visits_201505) 
  /Visits_201506=SUM(Visits_201506) 
  /Visits_201507=SUM(Visits_201507) 
  /Visits_201508=SUM(Visits_201508) 
  /Visits_201509=SUM(Visits_201509) 
  /Visits_201510=SUM(Visits_201510) 
  /Visits_201511=SUM(Visits_201511) 
  /Visits_201512=SUM(Visits_201512) 
  /Visits_201601=SUM(Visits_201601) 
  /Visits_201602=SUM(Visits_201602).

DATASET ACTIVATE PPC_VIS.

*Total PPC Revenue.
DATASET ACTIVATE PPC.

DATASET DECLARE PPC_REV.

AGGREGATE
  /OUTFILE='PPC_REV'
  /BREAK=Group
  /Revenue_201504=SUM(Revenue_201504) 
  /Revenue_201505=SUM(Revenue_201505) 
  /Revenue_201506=SUM(Revenue_201506) 
  /Revenue_201507=SUM(Revenue_201507) 
  /Revenue_201508=SUM(Revenue_201508) 
  /Revenue_201509=SUM(Revenue_201509) 
  /Revenue_201510=SUM(Revenue_201510) 
  /Revenue_201511=SUM(Revenue_201511) 
  /Revenue_201512=SUM(Revenue_201512) 
  /Revenue_201601=SUM(Revenue_201601) 
  /Revenue_201602=SUM(Revenue_201602).

DATASET ACTIVATE PPC_REV.
