*Get the GIS orders and sales by customer and zipcode from the customer table in Teradata.
GET DATA 
  /TYPE=ODBC 
  /CONNECT='DSN=Teradata;DB=PRD_DWH_VIEW;PORT=1025;DBCNL=10.4.165.29;UID=spss;PWD=$-<~*x#N3@!/-!!+'
  /SQL= 'SELECT CU.CUSTOMER, CU.ZZIPCD5 ZIPCODE, SI.ZORD_DATE, COUNT(DISTINCT SI.S_ORD_NUM) ORDERS, SUM(SI.SUBTOTAL_2) SALES ' +
             'FROM PRD_DWH_VIEW.Customer_V CU ' +
             'LEFT JOIN PRD_DWH_VIEW.Sales_Invoice_V SI '+
                'ON CU.CUSTOMER = SI.SOLD_TO '+
             'WHERE CU.ZZIPCD5 <> '''' AND ' +
                          'CU.ACCNT_GRP = ''0001'' AND ' +
                          'SI.ZZCOMFLG = ''Y'' AND ' +
                          'SI.ZORD_DATE BETWEEN {d ''2011-06-01''} AND {d ''2016-05-31''} AND ' +
                          'SI.SHIP_COND <> ''RE'' AND ' +
                          'SI.SUBTOTAL_2 > 0 '
             'GROUP BY CU.CUSTOMER, CU.ZZIPCD5, SI.ZORD_DATE '.
CACHE.
EXE.

DATASET NAME ACCT_ACT.
DATASET ACTIVATE ACCT_ACT.

STRING account(A10).
COMPUTE account = CUSTOMER.
EXE.

ALTER TYPE account(F10.0).

SORT CASES BY account(A) ZIPCODE(A) ZORD_DATE(A).

*Get the orders and sales for the accommodation account and zipcode from the customer table in Teradata.
GET DATA 
  /TYPE=ODBC 
  /CONNECT='DSN=Teradata;DB=PRD_DWH_VIEW;PORT=1025;DBCNL=10.4.165.29;UID=spss;PWD=$-<~*x#N3@!/-!!+'
  /SQL= 'SELECT SI.SOLD_TO, SI.ZSHIPZIP, SI.ZORD_DATE, COUNT(DISTINCT SI.S_ORD_NUM) ORDERS, SUM(SI.SUBTOTAL_2) SALES ' +
             'FROM PRD_DWH_VIEW.Sales_Invoice_V SI '+
             'WHERE SI.ZSHIPZIP <> '''' AND ' +
                          'SI.SOLD_TO = ''0222222226''  AND ' +
                          'SI.ZZCOMFLG = ''Y'' AND ' +
                          'SI.ZORD_DATE BETWEEN {d ''2011-06-01''} AND {d ''2016-05-31''} AND ' +
                          'SI.SHIP_COND <> ''RE'' AND ' +
                          'SI.SUBTOTAL_2 > 0 '
             'GROUP BY SI.SOLD_TO, SI.ZSHIPZIP, SI.ZORD_DATE '.
CACHE.
EXE.

DATASET NAME GUEST_ACT.
DATASET ACTIVATE GUEST_ACT.

STRING account(A10).
COMPUTE account = SOLD_TO.

STRING ZIPCODE(A5).
COMPUTE ZIPCODE = SUBSTR(ZSHIPZIP,1,5).
EXE.

ALTER TYPE account(F10.0).

DELETE VARIABLES ZSHIPZIP.

RENAME VARIABLES SOLD_TO = CUSTOMER.

SORT CASES BY account(A) ZIPCODE(A) ZORD_DATE(A).

ADD FILES
   /FILE = *
   /FILE = 'ACCT_ACT'.
EXE.

DATASET CLOSE ACCT_ACT.
DATASET ACTIVATE GUEST_ACT.
DATASET NAME ACCT_ACT.

*Get the month from the order date.
COMPUTE OM = XDATE.MONTH(ZORD_DATE).
COMPUTE OYR = XDATE.YEAR(ZORD_DATE).
EXE.

ALTER TYPE OM(A2) OYR(A4).

COMPUTE #cl = CHAR.LENGTH(LTRIM(OM)).

STRING ORD_MY(A6).

DO IF(#cl = 1).

   COMPUTE ORD_MY = CONCAT(OYR,'0',LTRIM(OM)).

ELSE.

   COMPUTE ORD_MY = CONCAT(OYR,OM).

END IF.
EXE.

ALTER TYPE ORD_MY(F6.0).

DELETE VARIABLES OM OYR.

*Aggregate the sales and orders by zipcode and the order month.
DATASET DECLARE ORD_BY_MZ.

AGGREGATE
   /OUTFILE = 'ORD_BY_MZ'
   /BREAK = account ORD_MY ZIPCODE
   /ORDERS = SUM(ORDERS)
   /SALES = SUM(SALES).

DATASET ACTIVATE ORD_BY_MZ.

DATASET DECLARE ACCT_ZIPS.

AGGREGATE
   /OUTFILE = 'ACCT_ZIPS'
   /BREAK = account ZIPCODE
   /Num_Records = N.

DATASET ACTIVATE ORD_BY_MZ.

*Change the layout from row wise to column wise.
DATASET COPY JUN11.
DATASET COPY JUL11.
DATASET COPY AUG11.
DATASET COPY SEP11.
DATASET COPY OCT11.
DATASET COPY NOV11.
DATASET COPY DEC11.

*June 2011.
DATASET ACTIVATE JUN11.

SELECT IF(ORD_MY = 201106).
EXE.

RENAME VARIABLES ORDERS = ORD_0611.
RENAME VARIABLES SALES = SLS_0611.

*July 2011.
DATASET ACTIVATE JUL11.

SELECT IF(ORD_MY = 201107).
EXE.

RENAME VARIABLES ORDERS = ORD_0711.
RENAME VARIABLES SALES = SLS_0711.

*July 2011.
DATASET ACTIVATE AUG11.

SELECT IF(ORD_MY = 201108).
EXE.

RENAME VARIABLES ORDERS = ORD_0811.
RENAME VARIABLES SALES = SLS_0811.

*Sept 2011.
DATASET ACTIVATE SEP11.

SELECT IF(ORD_MY = 201109).
EXE.

RENAME VARIABLES ORDERS = ORD_0911.
RENAME VARIABLES SALES = SLS_0911.

*Oct 2011.
DATASET ACTIVATE OCT11.

SELECT IF(ORD_MY = 201110).
EXE.

RENAME VARIABLES ORDERS = ORD_1011.
RENAME VARIABLES SALES = SLS_1011.

*Nov 2011.
DATASET ACTIVATE NOV11.

SELECT IF(ORD_MY = 201111).
EXE.

RENAME VARIABLES ORDERS = ORD_1111.
RENAME VARIABLES SALES = SLS_1111.

*December 2011.
DATASET ACTIVATE DEC11.

SELECT IF(ORD_MY = 201112).
EXE.

RENAME VARIABLES ORDERS = ORD_1211.
RENAME VARIABLES SALES = SLS_1211.

DATASET ACTIVATE ACCT_ZIPS.

DELETE VARIABLES Num_Records.

MATCH FILES
   /FILE = *
   /TABLE = 'JUN11'
   /TABLE = 'JUL11'
   /TABLE = 'AUG11'
   /TABLE = 'SEP11'
   /TABLE = 'OCT11'
   /TABLE = 'NOV11'
   /TABLE = 'DEC11'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JUN11.
DATASET CLOSE JUL11.
DATASET CLOSE AUG11.
DATASET CLOSE SEP11.
DATASET CLOSE OCT11.
DATASET CLOSE NOV11.
DATASET CLOSE DEC11.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN12.
DATASET COPY FEB12.
DATASET COPY MAR12.
DATASET COPY APR12.
DATASET COPY MAY12.
DATASET COPY JUN12.
DATASET COPY JUL12.
DATASET COPY AUG12.
DATASET COPY SEP12.
DATASET COPY OCT12.
DATASET COPY NOV12.
DATASET COPY DEC12.

*January 2012.
DATASET ACTIVATE JAN12.

SELECT IF(ORD_MY = 201201).
EXE.

RENAME VARIABLES ORDERS = ORD_0112.
RENAME VARIABLES SALES = SLS_0112.

*February 2012.
DATASET ACTIVATE FEB12.

SELECT IF(ORD_MY = 201202).
EXE.

RENAME VARIABLES ORDERS = ORD_0212.
RENAME VARIABLES SALES = SLS_0212.

*March 2012.
DATASET ACTIVATE MAR12.

SELECT IF(ORD_MY = 201203).
EXE.

RENAME VARIABLES ORDERS = ORD_0312.
RENAME VARIABLES SALES = SLS_0312.

*April 2012.
DATASET ACTIVATE APR12.

SELECT IF(ORD_MY = 201204).
EXE.

RENAME VARIABLES ORDERS = ORD_0412.
RENAME VARIABLES SALES = SLS_0412.

*May 2012.
DATASET ACTIVATE MAY12.

SELECT IF(ORD_MY = 201205).
EXE.

RENAME VARIABLES ORDERS = ORD_0512.
RENAME VARIABLES SALES = SLS_0512.

*June 2012.
DATASET ACTIVATE JUN12.

SELECT IF(ORD_MY = 201206).
EXE.

RENAME VARIABLES ORDERS = ORD_0612.
RENAME VARIABLES SALES = SLS_0612.

*July 2012.
DATASET ACTIVATE JUL12.

SELECT IF(ORD_MY = 201207).
EXE.

RENAME VARIABLES ORDERS = ORD_0712.
RENAME VARIABLES SALES = SLS_0712.

*July 2012.
DATASET ACTIVATE AUG12.

SELECT IF(ORD_MY = 201208).
EXE.

RENAME VARIABLES ORDERS = ORD_0812.
RENAME VARIABLES SALES = SLS_0812.

*Sept 2012.
DATASET ACTIVATE SEP12.

SELECT IF(ORD_MY = 201209).
EXE.

RENAME VARIABLES ORDERS = ORD_0912.
RENAME VARIABLES SALES = SLS_0912.

*Oct 2012.
DATASET ACTIVATE OCT12.

SELECT IF(ORD_MY = 201210).
EXE.

RENAME VARIABLES ORDERS = ORD_1012.
RENAME VARIABLES SALES = SLS_1012.

*Nov 2012.
DATASET ACTIVATE NOV12.

SELECT IF(ORD_MY = 201211).
EXE.

RENAME VARIABLES ORDERS = ORD_1112.
RENAME VARIABLES SALES = SLS_1112.

*December 2012.
DATASET ACTIVATE DEC12.

SELECT IF(ORD_MY = 201212).
EXE.

RENAME VARIABLES ORDERS = ORD_1212.
RENAME VARIABLES SALES = SLS_1212.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN12'
   /TABLE = 'FEB12'
   /TABLE = 'MAR12'
   /TABLE = 'APR12'
   /TABLE = 'MAY12'
   /TABLE = 'JUN12'
   /TABLE = 'JUL12'
   /TABLE = 'AUG12'
   /TABLE = 'SEP12'
   /TABLE = 'OCT12'
   /TABLE = 'NOV12'
   /TABLE = 'DEC12'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN12.
DATASET CLOSE FEB12.
DATASET CLOSE MAR12.
DATASET CLOSE APR12.
DATASET CLOSE MAY12.
DATASET CLOSE JUN12.
DATASET CLOSE JUL12.
DATASET CLOSE AUG12.
DATASET CLOSE SEP12.
DATASET CLOSE OCT12.
DATASET CLOSE NOV12.
DATASET CLOSE DEC12.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN13.
DATASET COPY FEB13.
DATASET COPY MAR13.
DATASET COPY APR13.
DATASET COPY MAY13.
DATASET COPY JUN13.
DATASET COPY JUL13.
DATASET COPY AUG13.
DATASET COPY SEP13.
DATASET COPY OCT13.
DATASET COPY NOV13.
DATASET COPY DEC13.

*January 2013.
DATASET ACTIVATE JAN13.

SELECT IF(ORD_MY = 201301).
EXE.

RENAME VARIABLES ORDERS = ORD_0113.
RENAME VARIABLES SALES = SLS_0113.

*February 2013.
DATASET ACTIVATE FEB13.

SELECT IF(ORD_MY = 201302).
EXE.

RENAME VARIABLES ORDERS = ORD_0213.
RENAME VARIABLES SALES = SLS_0213.

*March 2013.
DATASET ACTIVATE MAR13.

SELECT IF(ORD_MY = 201303).
EXE.

RENAME VARIABLES ORDERS = ORD_0313.
RENAME VARIABLES SALES = SLS_0313.

*April 2013.
DATASET ACTIVATE APR13.

SELECT IF(ORD_MY = 201304).
EXE.

RENAME VARIABLES ORDERS = ORD_0413.
RENAME VARIABLES SALES = SLS_0413.

*May 2013.
DATASET ACTIVATE MAY13.

SELECT IF(ORD_MY = 201305).
EXE.

RENAME VARIABLES ORDERS = ORD_0513.
RENAME VARIABLES SALES = SLS_0513.

*June 2013.
DATASET ACTIVATE JUN13.

SELECT IF(ORD_MY = 201306).
EXE.

RENAME VARIABLES ORDERS = ORD_0613.
RENAME VARIABLES SALES = SLS_0613.

*July 2013.
DATASET ACTIVATE JUL13.

SELECT IF(ORD_MY = 201307).
EXE.

RENAME VARIABLES ORDERS = ORD_0713.
RENAME VARIABLES SALES = SLS_0713.

*July 2013.
DATASET ACTIVATE AUG13.

SELECT IF(ORD_MY = 201308).
EXE.

RENAME VARIABLES ORDERS = ORD_0813.
RENAME VARIABLES SALES = SLS_0813.

*Sept 2013.
DATASET ACTIVATE SEP13.

SELECT IF(ORD_MY = 201309).
EXE.

RENAME VARIABLES ORDERS = ORD_0913.
RENAME VARIABLES SALES = SLS_0913.

*Oct 2013.
DATASET ACTIVATE OCT13.

SELECT IF(ORD_MY = 201310).
EXE.

RENAME VARIABLES ORDERS = ORD_1013.
RENAME VARIABLES SALES = SLS_1013.

*Nov 2013.
DATASET ACTIVATE NOV13.

SELECT IF(ORD_MY = 201311).
EXE.

RENAME VARIABLES ORDERS = ORD_1113.
RENAME VARIABLES SALES = SLS_1113.

*December 2013.
DATASET ACTIVATE DEC13.

SELECT IF(ORD_MY = 201312).
EXE.

RENAME VARIABLES ORDERS = ORD_1213.
RENAME VARIABLES SALES = SLS_1213.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN13'
   /TABLE = 'FEB13'
   /TABLE = 'MAR13'
   /TABLE = 'APR13'
   /TABLE = 'MAY13'
   /TABLE = 'JUN13'
   /TABLE = 'JUL13'
   /TABLE = 'AUG13'
   /TABLE = 'SEP13'
   /TABLE = 'OCT13'
   /TABLE = 'NOV13'
   /TABLE = 'DEC13'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN13.
DATASET CLOSE FEB13.
DATASET CLOSE MAR13.
DATASET CLOSE APR13.
DATASET CLOSE MAY13.
DATASET CLOSE JUN13.
DATASET CLOSE JUL13.
DATASET CLOSE AUG13.
DATASET CLOSE SEP13.
DATASET CLOSE OCT13.
DATASET CLOSE NOV13.
DATASET CLOSE DEC13.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN14.
DATASET COPY FEB14.
DATASET COPY MAR14.
DATASET COPY APR14.
DATASET COPY MAY14.
DATASET COPY JUN14.
DATASET COPY JUL14.
DATASET COPY AUG14.
DATASET COPY SEP14.
DATASET COPY OCT14.
DATASET COPY NOV14.
DATASET COPY DEC14.

*January 2014.
DATASET ACTIVATE JAN14.

SELECT IF(ORD_MY = 201401).
EXE.

RENAME VARIABLES ORDERS = ORD_0114.
RENAME VARIABLES SALES = SLS_0114.

*February 2014.
DATASET ACTIVATE FEB14.

SELECT IF(ORD_MY = 201402).
EXE.

RENAME VARIABLES ORDERS = ORD_0214.
RENAME VARIABLES SALES = SLS_0214.

*March 2014.
DATASET ACTIVATE MAR14.

SELECT IF(ORD_MY = 201403).
EXE.

RENAME VARIABLES ORDERS = ORD_0314.
RENAME VARIABLES SALES = SLS_0314.

*April 2014.
DATASET ACTIVATE APR14.

SELECT IF(ORD_MY = 201404).
EXE.

RENAME VARIABLES ORDERS = ORD_0414.
RENAME VARIABLES SALES = SLS_0414.

*May 2014.
DATASET ACTIVATE MAY14.

SELECT IF(ORD_MY = 201405).
EXE.

RENAME VARIABLES ORDERS = ORD_0514.
RENAME VARIABLES SALES = SLS_0514.

*June 2014.
DATASET ACTIVATE JUN14.

SELECT IF(ORD_MY = 201406).
EXE.

RENAME VARIABLES ORDERS = ORD_0614.
RENAME VARIABLES SALES = SLS_0614.

*July 2014.
DATASET ACTIVATE JUL14.

SELECT IF(ORD_MY = 201407).
EXE.

RENAME VARIABLES ORDERS = ORD_0714.
RENAME VARIABLES SALES = SLS_0714.

*July 2014.
DATASET ACTIVATE AUG14.

SELECT IF(ORD_MY = 201408).
EXE.

RENAME VARIABLES ORDERS = ORD_0814.
RENAME VARIABLES SALES = SLS_0814.

*Sept 2014.
DATASET ACTIVATE SEP14.

SELECT IF(ORD_MY = 201409).
EXE.

RENAME VARIABLES ORDERS = ORD_0914.
RENAME VARIABLES SALES = SLS_0914.

*Oct 2014.
DATASET ACTIVATE OCT14.

SELECT IF(ORD_MY = 201410).
EXE.

RENAME VARIABLES ORDERS = ORD_1014.
RENAME VARIABLES SALES = SLS_1014.

*Nov 2014.
DATASET ACTIVATE NOV14.

SELECT IF(ORD_MY = 201411).
EXE.

RENAME VARIABLES ORDERS = ORD_1114.
RENAME VARIABLES SALES = SLS_1114.

*December 2014.
DATASET ACTIVATE DEC14.

SELECT IF(ORD_MY = 201412).
EXE.

RENAME VARIABLES ORDERS = ORD_1214.
RENAME VARIABLES SALES = SLS_1214.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN14'
   /TABLE = 'FEB14'
   /TABLE = 'MAR14'
   /TABLE = 'APR14'
   /TABLE = 'MAY14'
   /TABLE = 'JUN14'
   /TABLE = 'JUL14'
   /TABLE = 'AUG14'
   /TABLE = 'SEP14'
   /TABLE = 'OCT14'
   /TABLE = 'NOV14'
   /TABLE = 'DEC14'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN14.
DATASET CLOSE FEB14.
DATASET CLOSE MAR14.
DATASET CLOSE APR14.
DATASET CLOSE MAY14.
DATASET CLOSE JUN14.
DATASET CLOSE JUL14.
DATASET CLOSE AUG14.
DATASET CLOSE SEP14.
DATASET CLOSE OCT14.
DATASET CLOSE NOV14.
DATASET CLOSE DEC14.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN15.
DATASET COPY FEB15.
DATASET COPY MAR15.
DATASET COPY APR15.
DATASET COPY MAY15.
DATASET COPY JUN15.
DATASET COPY JUL15.
DATASET COPY AUG15.
DATASET COPY SEP15.
DATASET COPY OCT15.
DATASET COPY NOV15.
DATASET COPY DEC15.

*January 2015.
DATASET ACTIVATE JAN15.

SELECT IF(ORD_MY = 201501).
EXE.

RENAME VARIABLES ORDERS = ORD_0115.
RENAME VARIABLES SALES = SLS_0115.

*February 2015.
DATASET ACTIVATE FEB15.

SELECT IF(ORD_MY = 201502).
EXE.

RENAME VARIABLES ORDERS = ORD_0215.
RENAME VARIABLES SALES = SLS_0215.

*March 2015.
DATASET ACTIVATE MAR15.

SELECT IF(ORD_MY = 201503).
EXE.

RENAME VARIABLES ORDERS = ORD_0315.
RENAME VARIABLES SALES = SLS_0315.

*April 2015.
DATASET ACTIVATE APR15.

SELECT IF(ORD_MY = 201504).
EXE.

RENAME VARIABLES ORDERS = ORD_0415.
RENAME VARIABLES SALES = SLS_0415.

*May 2015.
DATASET ACTIVATE MAY15.

SELECT IF(ORD_MY = 201505).
EXE.

RENAME VARIABLES ORDERS = ORD_0515.
RENAME VARIABLES SALES = SLS_0515.

*June 2015.
DATASET ACTIVATE JUN15.

SELECT IF(ORD_MY = 201506).
EXE.

RENAME VARIABLES ORDERS = ORD_0615.
RENAME VARIABLES SALES = SLS_0615.

*July 2015.
DATASET ACTIVATE JUL15.

SELECT IF(ORD_MY = 201507).
EXE.

RENAME VARIABLES ORDERS = ORD_0715.
RENAME VARIABLES SALES = SLS_0715.

*July 2015.
DATASET ACTIVATE AUG15.

SELECT IF(ORD_MY = 201508).
EXE.

RENAME VARIABLES ORDERS = ORD_0815.
RENAME VARIABLES SALES = SLS_0815.

*Sept 2015.
DATASET ACTIVATE SEP15.

SELECT IF(ORD_MY = 201509).
EXE.

RENAME VARIABLES ORDERS = ORD_0915.
RENAME VARIABLES SALES = SLS_0915.

*Oct 2015.
DATASET ACTIVATE OCT15.

SELECT IF(ORD_MY = 201510).
EXE.

RENAME VARIABLES ORDERS = ORD_1015.
RENAME VARIABLES SALES = SLS_1015.

*Nov 2015.
DATASET ACTIVATE NOV15.

SELECT IF(ORD_MY = 201511).
EXE.

RENAME VARIABLES ORDERS = ORD_1115.
RENAME VARIABLES SALES = SLS_1115.

*December 2015.
DATASET ACTIVATE DEC15.

SELECT IF(ORD_MY = 201512).
EXE.

RENAME VARIABLES ORDERS = ORD_1215.
RENAME VARIABLES SALES = SLS_1215.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN15'
   /TABLE = 'FEB15'
   /TABLE = 'MAR15'
   /TABLE = 'APR15'
   /TABLE = 'MAY15'
   /TABLE = 'JUN15'
   /TABLE = 'JUL15'
   /TABLE = 'AUG15'
   /TABLE = 'SEP15'
   /TABLE = 'OCT15'
   /TABLE = 'NOV15'
   /TABLE = 'DEC15'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN15.
DATASET CLOSE FEB15.
DATASET CLOSE MAR15.
DATASET CLOSE APR15.
DATASET CLOSE MAY15.
DATASET CLOSE JUN15.
DATASET CLOSE JUL15.
DATASET CLOSE AUG15.
DATASET CLOSE SEP15.
DATASET CLOSE OCT15.
DATASET CLOSE NOV15.
DATASET CLOSE DEC15.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN16.
DATASET COPY FEB16.
DATASET COPY MAR16.
DATASET COPY APR16.
DATASET COPY MAY16.

*January 2016.
DATASET ACTIVATE JAN16.

SELECT IF(ORD_MY = 201601).
EXE.

RENAME VARIABLES ORDERS = ORD_0116.
RENAME VARIABLES SALES = SLS_0116.

*February 2016.
DATASET ACTIVATE FEB16.

SELECT IF(ORD_MY = 201602).
EXE.

RENAME VARIABLES ORDERS = ORD_0216.
RENAME VARIABLES SALES = SLS_0216.

*March 2016.
DATASET ACTIVATE MAR16.

SELECT IF(ORD_MY = 201603).
EXE.

RENAME VARIABLES ORDERS = ORD_0316.
RENAME VARIABLES SALES = SLS_0316.

*April 2016.
DATASET ACTIVATE APR16.

SELECT IF(ORD_MY = 201604).
EXE.

RENAME VARIABLES ORDERS = ORD_0416.
RENAME VARIABLES SALES = SLS_0416.

*May 2016.
DATASET ACTIVATE MAY16.

SELECT IF(ORD_MY = 201605).
EXE.

RENAME VARIABLES ORDERS = ORD_0516.
RENAME VARIABLES SALES = SLS_0516.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN16'
   /TABLE = 'FEB16'
   /TABLE = 'MAR16'
   /TABLE = 'APR16'
   /TABLE = 'MAY16'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN16.
DATASET CLOSE FEB16.
DATASET CLOSE MAR16.
DATASET CLOSE APR16.
DATASET CLOSE MAY16.
DATASET CLOSE ORD_BY_MZ.

DATASET ACTIVATE ACCT_ZIPS.

DELETE VARIABLES ORD_MY.









*Get the Gcom orders and sales by customer and zipcode from the customer table in Teradata.
GET DATA 
  /TYPE=ODBC 
  /CONNECT='DSN=Teradata;DB=PRD_DWH_VIEW;PORT=1025;DBCNL=10.4.165.29;UID=spss;PWD=$-<~*x#N3@!/-!!+'
  /SQL= 'SELECT CU.CUSTOMER, CU.ZZIPCD5 ZIPCODE, SI.ZORD_DATE, COUNT(DISTINCT SI.S_ORD_NUM) ORDERS, SUM(SI.SUBTOTAL_2) SALES ' +
             'FROM PRD_DWH_VIEW.Customer_V CU ' +
             'LEFT JOIN PRD_DWH_VIEW.Sales_Invoice_V SI '+
                'ON CU.CUSTOMER = SI.SOLD_TO '+
             'WHERE CU.ZZIPCD5 <> '''' AND ' +
                          'CU.ACCNT_GRP = ''0001'' AND ' +
                          'SI.ZZCOMFLG = ''Y'' AND ' +
                          'SI.ZORD_DATE BETWEEN {d ''2011-06-01''} AND {d ''2016-05-31''} AND ' +
                          'SI.SHIP_COND <> ''RE'' AND ' +
                          'SI.SUBTOTAL_2 > 0 AND ' +
                          'SI.SALES_OFF = ''E01'' ' +
             'GROUP BY CU.CUSTOMER, CU.ZZIPCD5, SI.ZORD_DATE '.
CACHE.
EXE.

DATASET NAME ACCT_GC_ACT.
DATASET ACTIVATE ACCT_GC_ACT.

STRING account(A10).
COMPUTE account = CUSTOMER.
EXE.

ALTER TYPE account(F10.0).

SORT CASES BY account(A) ZIPCODE(A) ZORD_DATE(A).

*Get the month from the order date.
COMPUTE OM = XDATE.MONTH(ZORD_DATE).
COMPUTE OYR = XDATE.YEAR(ZORD_DATE).
EXE.

ALTER TYPE OM(A2) OYR(A4).

COMPUTE #cl = CHAR.LENGTH(LTRIM(OM)).

STRING ORD_MY(A6).

DO IF(#cl = 1).

   COMPUTE ORD_MY = CONCAT(OYR,'0',LTRIM(OM)).

ELSE.

   COMPUTE ORD_MY = CONCAT(OYR,OM).

END IF.
EXE.

ALTER TYPE ORD_MY(F6.0).

DELETE VARIABLES OM OYR.

*Aggregate the sales and orders by zipcode and the order month.
DATASET DECLARE ORD_BY_MZ.

AGGREGATE
   /OUTFILE = 'ORD_BY_MZ'
   /BREAK = account ORD_MY ZIPCODE
   /ORDERS = SUM(ORDERS)
   /SALES = SUM(SALES).

DATASET ACTIVATE ORD_BY_MZ.

DATASET DECLARE ACCT_ZIPS_GC.

AGGREGATE
   /OUTFILE = 'ACCT_ZIPS_GC'
   /BREAK = account ZIPCODE
   /Num_Records = N.

DATASET ACTIVATE ORD_BY_MZ.

*Change the layout from row wise to column wise.
DATASET COPY JUN11.
DATASET COPY JUL11.
DATASET COPY AUG11.
DATASET COPY SEP11.
DATASET COPY OCT11.
DATASET COPY NOV11.
DATASET COPY DEC11.

*June 2011.
DATASET ACTIVATE JUN11.

SELECT IF(ORD_MY = 201106).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0611.
RENAME VARIABLES SALES = GC_SLS_0611.

*July 2011.
DATASET ACTIVATE JUL11.

SELECT IF(ORD_MY = 201107).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0711.
RENAME VARIABLES SALES = GC_SLS_0711.

*July 2011.
DATASET ACTIVATE AUG11.

SELECT IF(ORD_MY = 201108).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0811.
RENAME VARIABLES SALES = GC_SLS_0811.

*Sept 2011.
DATASET ACTIVATE SEP11.

SELECT IF(ORD_MY = 201109).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0911.
RENAME VARIABLES SALES = GC_SLS_0911.

*Oct 2011.
DATASET ACTIVATE OCT11.

SELECT IF(ORD_MY = 201110).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1011.
RENAME VARIABLES SALES = GC_SLS_1011.

*Nov 2011.
DATASET ACTIVATE NOV11.

SELECT IF(ORD_MY = 201111).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1111.
RENAME VARIABLES SALES = GC_SLS_1111.

*December 2011.
DATASET ACTIVATE DEC11.

SELECT IF(ORD_MY = 201112).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1211.
RENAME VARIABLES SALES = GC_SLS_1211.

DATASET ACTIVATE ACCT_ZIPS_GC.

DELETE VARIABLES Num_Records.

MATCH FILES
   /FILE = *
   /TABLE = 'JUN11'
   /TABLE = 'JUL11'
   /TABLE = 'AUG11'
   /TABLE = 'SEP11'
   /TABLE = 'OCT11'
   /TABLE = 'NOV11'
   /TABLE = 'DEC11'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JUN11.
DATASET CLOSE JUL11.
DATASET CLOSE AUG11.
DATASET CLOSE SEP11.
DATASET CLOSE OCT11.
DATASET CLOSE NOV11.
DATASET CLOSE DEC11.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN12.
DATASET COPY FEB12.
DATASET COPY MAR12.
DATASET COPY APR12.
DATASET COPY MAY12.
DATASET COPY JUN12.
DATASET COPY JUL12.
DATASET COPY AUG12.
DATASET COPY SEP12.
DATASET COPY OCT12.
DATASET COPY NOV12.
DATASET COPY DEC12.

*January 2012.
DATASET ACTIVATE JAN12.

SELECT IF(ORD_MY = 201201).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0112.
RENAME VARIABLES SALES = GC_SLS_0112.

*February 2012.
DATASET ACTIVATE FEB12.

SELECT IF(ORD_MY = 201202).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0212.
RENAME VARIABLES SALES = GC_SLS_0212.

*March 2012.
DATASET ACTIVATE MAR12.

SELECT IF(ORD_MY = 201203).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0312.
RENAME VARIABLES SALES = GC_SLS_0312.

*April 2012.
DATASET ACTIVATE APR12.

SELECT IF(ORD_MY = 201204).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0412.
RENAME VARIABLES SALES = GC_SLS_0412.

*May 2012.
DATASET ACTIVATE MAY12.

SELECT IF(ORD_MY = 201205).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0512.
RENAME VARIABLES SALES = GC_SLS_0512.

*June 2012.
DATASET ACTIVATE JUN12.

SELECT IF(ORD_MY = 201206).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0612.
RENAME VARIABLES SALES = GC_SLS_0612.

*July 2012.
DATASET ACTIVATE JUL12.

SELECT IF(ORD_MY = 201207).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0712.
RENAME VARIABLES SALES = GC_SLS_0712.

*July 2012.
DATASET ACTIVATE AUG12.

SELECT IF(ORD_MY = 201208).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0812.
RENAME VARIABLES SALES = GC_SLS_0812.

*Sept 2012.
DATASET ACTIVATE SEP12.

SELECT IF(ORD_MY = 201209).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0912.
RENAME VARIABLES SALES = GC_SLS_0912.

*Oct 2012.
DATASET ACTIVATE OCT12.

SELECT IF(ORD_MY = 201210).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1012.
RENAME VARIABLES SALES = GC_SLS_1012.

*Nov 2012.
DATASET ACTIVATE NOV12.

SELECT IF(ORD_MY = 201211).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1112.
RENAME VARIABLES SALES = GC_SLS_1112.

*December 2012.
DATASET ACTIVATE DEC12.

SELECT IF(ORD_MY = 201212).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1212.
RENAME VARIABLES SALES = GC_SLS_1212.

DATASET ACTIVATE ACCT_ZIPS_GC.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN12'
   /TABLE = 'FEB12'
   /TABLE = 'MAR12'
   /TABLE = 'APR12'
   /TABLE = 'MAY12'
   /TABLE = 'JUN12'
   /TABLE = 'JUL12'
   /TABLE = 'AUG12'
   /TABLE = 'SEP12'
   /TABLE = 'OCT12'
   /TABLE = 'NOV12'
   /TABLE = 'DEC12'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN12.
DATASET CLOSE FEB12.
DATASET CLOSE MAR12.
DATASET CLOSE APR12.
DATASET CLOSE MAY12.
DATASET CLOSE JUN12.
DATASET CLOSE JUL12.
DATASET CLOSE AUG12.
DATASET CLOSE SEP12.
DATASET CLOSE OCT12.
DATASET CLOSE NOV12.
DATASET CLOSE DEC12.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN13.
DATASET COPY FEB13.
DATASET COPY MAR13.
DATASET COPY APR13.
DATASET COPY MAY13.
DATASET COPY JUN13.
DATASET COPY JUL13.
DATASET COPY AUG13.
DATASET COPY SEP13.
DATASET COPY OCT13.
DATASET COPY NOV13.
DATASET COPY DEC13.

*January 2013.
DATASET ACTIVATE JAN13.

SELECT IF(ORD_MY = 201301).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0113.
RENAME VARIABLES SALES = GC_SLS_0113.

*February 2013.
DATASET ACTIVATE FEB13.

SELECT IF(ORD_MY = 201302).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0213.
RENAME VARIABLES SALES = GC_SLS_0213.

*March 2013.
DATASET ACTIVATE MAR13.

SELECT IF(ORD_MY = 201303).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0313.
RENAME VARIABLES SALES = GC_SLS_0313.

*April 2013.
DATASET ACTIVATE APR13.

SELECT IF(ORD_MY = 201304).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0413.
RENAME VARIABLES SALES = GC_SLS_0413.

*May 2013.
DATASET ACTIVATE MAY13.

SELECT IF(ORD_MY = 201305).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0513.
RENAME VARIABLES SALES = GC_SLS_0513.

*June 2013.
DATASET ACTIVATE JUN13.

SELECT IF(ORD_MY = 201306).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0613.
RENAME VARIABLES SALES = GC_SLS_0613.

*July 2013.
DATASET ACTIVATE JUL13.

SELECT IF(ORD_MY = 201307).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0713.
RENAME VARIABLES SALES = GC_SLS_0713.

*July 2013.
DATASET ACTIVATE AUG13.

SELECT IF(ORD_MY = 201308).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0813.
RENAME VARIABLES SALES = GC_SLS_0813.

*Sept 2013.
DATASET ACTIVATE SEP13.

SELECT IF(ORD_MY = 201309).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0913.
RENAME VARIABLES SALES = GC_SLS_0913.

*Oct 2013.
DATASET ACTIVATE OCT13.

SELECT IF(ORD_MY = 201310).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1013.
RENAME VARIABLES SALES = GC_SLS_1013.

*Nov 2013.
DATASET ACTIVATE NOV13.

SELECT IF(ORD_MY = 201311).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1113.
RENAME VARIABLES SALES = GC_SLS_1113.

*December 2013.
DATASET ACTIVATE DEC13.

SELECT IF(ORD_MY = 201312).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1213.
RENAME VARIABLES SALES = GC_SLS_1213.

DATASET ACTIVATE ACCT_ZIPS_GC.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN13'
   /TABLE = 'FEB13'
   /TABLE = 'MAR13'
   /TABLE = 'APR13'
   /TABLE = 'MAY13'
   /TABLE = 'JUN13'
   /TABLE = 'JUL13'
   /TABLE = 'AUG13'
   /TABLE = 'SEP13'
   /TABLE = 'OCT13'
   /TABLE = 'NOV13'
   /TABLE = 'DEC13'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN13.
DATASET CLOSE FEB13.
DATASET CLOSE MAR13.
DATASET CLOSE APR13.
DATASET CLOSE MAY13.
DATASET CLOSE JUN13.
DATASET CLOSE JUL13.
DATASET CLOSE AUG13.
DATASET CLOSE SEP13.
DATASET CLOSE OCT13.
DATASET CLOSE NOV13.
DATASET CLOSE DEC13.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN14.
DATASET COPY FEB14.
DATASET COPY MAR14.
DATASET COPY APR14.
DATASET COPY MAY14.
DATASET COPY JUN14.
DATASET COPY JUL14.
DATASET COPY AUG14.
DATASET COPY SEP14.
DATASET COPY OCT14.
DATASET COPY NOV14.
DATASET COPY DEC14.

*January 2014.
DATASET ACTIVATE JAN14.

SELECT IF(ORD_MY = 201401).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0114.
RENAME VARIABLES SALES = GC_SLS_0114.

*February 2014.
DATASET ACTIVATE FEB14.

SELECT IF(ORD_MY = 201402).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0214.
RENAME VARIABLES SALES = GC_SLS_0214.

*March 2014.
DATASET ACTIVATE MAR14.

SELECT IF(ORD_MY = 201403).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0314.
RENAME VARIABLES SALES = GC_SLS_0314.

*April 2014.
DATASET ACTIVATE APR14.

SELECT IF(ORD_MY = 201404).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0414.
RENAME VARIABLES SALES = GC_SLS_0414.

*May 2014.
DATASET ACTIVATE MAY14.

SELECT IF(ORD_MY = 201405).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0514.
RENAME VARIABLES SALES = GC_SLS_0514.

*June 2014.
DATASET ACTIVATE JUN14.

SELECT IF(ORD_MY = 201406).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0614.
RENAME VARIABLES SALES = GC_SLS_0614.

*July 2014.
DATASET ACTIVATE JUL14.

SELECT IF(ORD_MY = 201407).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0714.
RENAME VARIABLES SALES = GC_SLS_0714.

*July 2014.
DATASET ACTIVATE AUG14.

SELECT IF(ORD_MY = 201408).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0814.
RENAME VARIABLES SALES = GC_SLS_0814.

*Sept 2014.
DATASET ACTIVATE SEP14.

SELECT IF(ORD_MY = 201409).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0914.
RENAME VARIABLES SALES = GC_SLS_0914.

*Oct 2014.
DATASET ACTIVATE OCT14.

SELECT IF(ORD_MY = 201410).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1014.
RENAME VARIABLES SALES = GC_SLS_1014.

*Nov 2014.
DATASET ACTIVATE NOV14.

SELECT IF(ORD_MY = 201411).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1114.
RENAME VARIABLES SALES = GC_SLS_1114.

*December 2014.
DATASET ACTIVATE DEC14.

SELECT IF(ORD_MY = 201412).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1214.
RENAME VARIABLES SALES = GC_SLS_1214.

DATASET ACTIVATE ACCT_ZIPS_GC.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN14'
   /TABLE = 'FEB14'
   /TABLE = 'MAR14'
   /TABLE = 'APR14'
   /TABLE = 'MAY14'
   /TABLE = 'JUN14'
   /TABLE = 'JUL14'
   /TABLE = 'AUG14'
   /TABLE = 'SEP14'
   /TABLE = 'OCT14'
   /TABLE = 'NOV14'
   /TABLE = 'DEC14'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN14.
DATASET CLOSE FEB14.
DATASET CLOSE MAR14.
DATASET CLOSE APR14.
DATASET CLOSE MAY14.
DATASET CLOSE JUN14.
DATASET CLOSE JUL14.
DATASET CLOSE AUG14.
DATASET CLOSE SEP14.
DATASET CLOSE OCT14.
DATASET CLOSE NOV14.
DATASET CLOSE DEC14.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN15.
DATASET COPY FEB15.
DATASET COPY MAR15.
DATASET COPY APR15.
DATASET COPY MAY15.
DATASET COPY JUN15.
DATASET COPY JUL15.
DATASET COPY AUG15.
DATASET COPY SEP15.
DATASET COPY OCT15.
DATASET COPY NOV15.
DATASET COPY DEC15.

*January 2015.
DATASET ACTIVATE JAN15.

SELECT IF(ORD_MY = 201501).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0115.
RENAME VARIABLES SALES = GC_SLS_0115.

*February 2015.
DATASET ACTIVATE FEB15.

SELECT IF(ORD_MY = 201502).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0215.
RENAME VARIABLES SALES = GC_SLS_0215.

*March 2015.
DATASET ACTIVATE MAR15.

SELECT IF(ORD_MY = 201503).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0315.
RENAME VARIABLES SALES = GC_SLS_0315.

*April 2015.
DATASET ACTIVATE APR15.

SELECT IF(ORD_MY = 201504).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0415.
RENAME VARIABLES SALES = GC_SLS_0415.

*May 2015.
DATASET ACTIVATE MAY15.

SELECT IF(ORD_MY = 201505).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0515.
RENAME VARIABLES SALES = GC_SLS_0515.

*June 2015.
DATASET ACTIVATE JUN15.

SELECT IF(ORD_MY = 201506).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0615.
RENAME VARIABLES SALES = GC_SLS_0615.

*July 2015.
DATASET ACTIVATE JUL15.

SELECT IF(ORD_MY = 201507).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0715.
RENAME VARIABLES SALES = GC_SLS_0715.

*July 2015.
DATASET ACTIVATE AUG15.

SELECT IF(ORD_MY = 201508).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0815.
RENAME VARIABLES SALES = GC_SLS_0815.

*Sept 2015.
DATASET ACTIVATE SEP15.

SELECT IF(ORD_MY = 201509).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0915.
RENAME VARIABLES SALES = GC_SLS_0915.

*Oct 2015.
DATASET ACTIVATE OCT15.

SELECT IF(ORD_MY = 201510).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1015.
RENAME VARIABLES SALES = GC_SLS_1015.

*Nov 2015.
DATASET ACTIVATE NOV15.

SELECT IF(ORD_MY = 201511).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1115.
RENAME VARIABLES SALES = GC_SLS_1115.

*December 2015.
DATASET ACTIVATE DEC15.

SELECT IF(ORD_MY = 201512).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_1215.
RENAME VARIABLES SALES = GC_SLS_1215.

DATASET ACTIVATE ACCT_ZIPS_GC.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN15'
   /TABLE = 'FEB15'
   /TABLE = 'MAR15'
   /TABLE = 'APR15'
   /TABLE = 'MAY15'
   /TABLE = 'JUN15'
   /TABLE = 'JUL15'
   /TABLE = 'AUG15'
   /TABLE = 'SEP15'
   /TABLE = 'OCT15'
   /TABLE = 'NOV15'
   /TABLE = 'DEC15'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN15.
DATASET CLOSE FEB15.
DATASET CLOSE MAR15.
DATASET CLOSE APR15.
DATASET CLOSE MAY15.
DATASET CLOSE JUN15.
DATASET CLOSE JUL15.
DATASET CLOSE AUG15.
DATASET CLOSE SEP15.
DATASET CLOSE OCT15.
DATASET CLOSE NOV15.
DATASET CLOSE DEC15.

DATASET ACTIVATE ORD_BY_MZ.

DATASET COPY JAN16.
DATASET COPY FEB16.
DATASET COPY MAR16.
DATASET COPY APR16.
DATASET COPY MAY16.

*January 2016.
DATASET ACTIVATE JAN16.

SELECT IF(ORD_MY = 201601).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0116.
RENAME VARIABLES SALES = GC_SLS_0116.

*February 2016.
DATASET ACTIVATE FEB16.

SELECT IF(ORD_MY = 201602).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0216.
RENAME VARIABLES SALES = GC_SLS_0216.

*March 2016.
DATASET ACTIVATE MAR16.

SELECT IF(ORD_MY = 201603).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0316.
RENAME VARIABLES SALES = GC_SLS_0316.

*April 2016.
DATASET ACTIVATE APR16.

SELECT IF(ORD_MY = 201604).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0416.
RENAME VARIABLES SALES = GC_SLS_0416.

*May 2016.
DATASET ACTIVATE MAY16.

SELECT IF(ORD_MY = 201605).
EXE.

RENAME VARIABLES ORDERS = GC_ORD_0516.
RENAME VARIABLES SALES = GC_SLS_0516.

DATASET ACTIVATE ACCT_ZIPS_GC.

MATCH FILES
   /FILE = *
   /TABLE = 'JAN16'
   /TABLE = 'FEB16'
   /TABLE = 'MAR16'
   /TABLE = 'APR16'
   /TABLE = 'MAY16'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE JAN16.
DATASET CLOSE FEB16.
DATASET CLOSE MAR16.
DATASET CLOSE APR16.
DATASET CLOSE MAY16.
DATASET CLOSE ORD_BY_MZ.

DATASET ACTIVATE ACCT_ZIPS_GC.

DELETE VARIABLES ORD_MY.

DATASET ACTIVATE ACCT_ZIPS.

MATCH FILES
   /FILE = *
   /TABLE = 'ACCT_ZIPS_GC'
   /BY account ZIPCODE.
EXE.

DATASET CLOSE ACCT_ZIPS_GC.
DATASET ACTIVATE ACCT_ZIPS.
DATASET NAME ACCTS.

*Loop through the data and populate Gcom sales with the GIS sales for the accommodation account (222222226).
VECTOR GIS = ORD_0611 TO SLS_0516.
VECTOR GC = GC_ORD_0611 TO GC_SLS_0516.

LOOP #i = 1 TO 120.

   IF(account = 222222226 AND MISSING(GC(#i))) GC(#i) = GIS(#i).

END LOOP.

*Recode missing values to 0.
VECTOR ACT = ORD_0611 TO GC_SLS_0516.

LOOP #j = 1 TO 240.

   IF(MISSING(ACT(#j))) ACT(#j) = 0.

END LOOP.
EXE.

*Open the sales days files to standardize sales for the number of sales days.
GET FILE = '/usr/spss/userdata/sales_days/2014-12-03 sales days thru 2022.sav'.
CACHE.
EXE.

DATASET NAME SD.
DATASET ACTIVATE SD.

*Select only the date range we need.
SELECT IF(month >= 201106 AND month <= 201605).
EXE.

*Transpose the records.
FLIP VARIABLES=slsdays
  /NEWNAMES=month.

DATASET NAME SALES_DAYS.
DATASET CLOSE SD.
DATASET ACTIVATE ACCTS.

STRING CASE_LBL(A7).

COMPUTE CASE_LBL = 'slsdays'.
EXE.

MATCH FILES
   /FILE = *
   /TABLE = 'SALES_DAYS'
   /BY CASE_LBL.
EXE.

DATASET CLOSE SALES_DAYS.
DATASET ACTIVATE ACCTS.

DELETE VARIABLES CASE_LBL.

VECTOR MO = ORD_0611 TO ORD_0516.
VECTOR MS = SLS_0611 TO SLS_0516.
VECTOR MGCO = GC_ORD_0611 TO GC_ORD_0516.
VECTOR MGCS = GC_SLS_0611 TO GC_SLS_0516.
VECTOR SD = K_201106 TO K_201605.

VECTOR ADO(60).
VECTOR ADS(60).
VECTOR ADGCO(60).
VECTOR ADGCS(60).

LOOP #k = 1 TO 60.

   DO IF(SD(#k) > 0).

      COMPUTE ADO(#k) = MO(#k) / SD(#k).
      COMPUTE ADS(#k) = MS(#k) / SD(#k).
      COMPUTE ADGCO(#k) = MGCO(#k) / SD(#k).
      COMPUTE ADGCS(#k) = MGCS(#k) / SD(#k).

   END IF.

END LOOP.

*Flag accounts who have orders in at least 1 month in the time period at which we are looking.
VECTOR TOT_ORD = ORD_0611 TO ORD_0516.

COMPUTE Has_Order = 0.
FORMATS Has_Order(F1.0).

LOOP #m = 1 TO 60.

   IF(TOT_ORD(#m) > 0) Has_Order = 1.

END LOOP.
EXE.

FREQ Has_Order.

DELETE VARIABLES K_201106 TO K_201605.

*Add in the DMA using the zip code of the account.
SORT CASES BY ZIPCODE(A).

*Open the file containing the Zipcode to DMA mapping.
GET FILE = '/usr/spss/userdata/LWhately/Media/2015 Media Test/dma_zip_xref_mine.sav'
   /KEEP ZipCode DMA.
CACHE.
EXE.

DATASET NAME DMA.
DATASET ACTIVATE DMA.

SORT CASES BY ZIPCODE(A).

DATASET ACTIVATE ACCTS.

MATCH FILES
   /FILE = *
   /TABLE = 'DMA'
   /BY ZIPCODE.
EXE.

DATASET CLOSE DMA.
DATASET ACTIVATE ACCTS.

SORT CASES BY account(A).

COMPUTE Group = 0.
IF(ANY(DMA,'ERIE','PEORIA - BLOOMINGTON','BIRMINGHAM (ANN & TUSC)','KNOXVILLE','FARGO - VALLEY CITY','LAS VEGAS')) Group = 1.
IF(ANY(DMA, 'AUGUSTA - AIKEN','SPRINGFIELD - HOLYOKE','FRESNO - VISALIA','LEXINGTON','JACKSON, MS','MADISON')) Group = 2.
IF(ANY(DMA,'BLUEFIELD - BECKLEY - OAK HILL','FT- SMITH - FAY - SPRNGDL - RG','RICHMOND - PETERSBURG', 
                    'GREENSBORO - H- POINT - W- SAL','LA CROSSE - EAU CLAIRE','TUCSON (SIERRA VISTA)')) Group = 3.
IF(ANY(DMA, 'DAVENPORT - R- ISLAND - MOLINE','YOUNGSTOWN','LANSING','GREENVLL - SPART - ASHEVLL - A','OMAHA','SIOUX CITY')) Group = 4.
FORMATS Group(F1.0).
EXE.

*Compute the natural log of avg monthly orders over the 5 year history used for the forecast.
DO IF(Has_Order = 1).

   COMPUTE ORD_PM = (SUM(ORD_0611 TO ORD_0516) / 60).
   COMPUTE ORD_PM_LN = LN(ORD_PM).

   *Compute the natural log of the monthly standard deviation of avg daily orders over the last 5 years.
   COMPUTE ORD_SD = SD(ADO1 TO ADO60).
   COMPUTE ORD_SD_LN = LN(ORD_SD).

END IF.

*Flag the accounts whose LN of Orders per Month is > 5.8.
COMPUTE Order_Outlier = (ORD_PM_LN > 5.8).
FORMATS Order_Outlier(F1.0).

*Flag the accounts whose LN of std deviation is >= 1.
COMPUTE Stable_Order_Outlier = (ORD_SD_LN >= 1).
FORMATS Stable_Order_Outlier(F1.0).

*Remove records that do not have sales as well as an Amazon account which location is aligned to both Seattle and Lexington.
COMPUTE Include = (Has_Order = 1 AND account <> 855313060 AND Order_Outlier = 0 AND Stable_Order_Outlier = 0).
FORMATS Include(F1.0).
EXE.

*Save the resulting file.
SAVE OUTFILE = '/usr/spss/userdata/Albrecht/PPC Geo/Weekly Updates/Final Analysis/June 11 to May 16 Sales and Orders by Account from TD.sav'.

SELECT IF(Group > 0).
EXE.

FILTER BY Include.

*Aggregate the average daily orders by group.
DATASET DECLARE ADO.

AGGREGATE
  /OUTFILE='ADO'
  /BREAK=Group
  /ADO1=SUM(ADO1) 
  /ADO2=SUM(ADO2) 
  /ADO3=SUM(ADO3) 
  /ADO4=SUM(ADO4) 
  /ADO5=SUM(ADO5) 
  /ADO6=SUM(ADO6) 
  /ADO7=SUM(ADO7) 
  /ADO8=SUM(ADO8) 
  /ADO9=SUM(ADO9) 
  /ADO10=SUM(ADO10) 
  /ADO11=SUM(ADO11) 
  /ADO12=SUM(ADO12) 
  /ADO13=SUM(ADO13) 
  /ADO14=SUM(ADO14) 
  /ADO15=SUM(ADO15) 
  /ADO16=SUM(ADO16) 
  /ADO17=SUM(ADO17) 
  /ADO18=SUM(ADO18) 
  /ADO19=SUM(ADO19) 
  /ADO20=SUM(ADO20) 
  /ADO21=SUM(ADO21) 
  /ADO22=SUM(ADO22) 
  /ADO23=SUM(ADO23) 
  /ADO24=SUM(ADO24) 
  /ADO25=SUM(ADO25) 
  /ADO26=SUM(ADO26) 
  /ADO27=SUM(ADO27) 
  /ADO28=SUM(ADO28) 
  /ADO29=SUM(ADO29) 
  /ADO30=SUM(ADO30) 
  /ADO31=SUM(ADO31) 
  /ADO32=SUM(ADO32) 
  /ADO33=SUM(ADO33) 
  /ADO34=SUM(ADO34) 
  /ADO35=SUM(ADO35) 
  /ADO36=SUM(ADO36) 
  /ADO37=SUM(ADO37) 
  /ADO38=SUM(ADO38) 
  /ADO39=SUM(ADO39) 
  /ADO40=SUM(ADO40) 
  /ADO41=SUM(ADO41) 
  /ADO42=SUM(ADO42) 
  /ADO43=SUM(ADO43) 
  /ADO44=SUM(ADO44) 
  /ADO45=SUM(ADO45) 
  /ADO46=SUM(ADO46) 
  /ADO47=SUM(ADO47) 
  /ADO48=SUM(ADO48) 
  /ADO49=SUM(ADO49) 
  /ADO50=SUM(ADO50) 
  /ADO51=SUM(ADO51) 
  /ADO52=SUM(ADO52) 
  /ADO53=SUM(ADO53) 
  /ADO54=SUM(ADO54) 
  /ADO55=SUM(ADO55) 
  /ADO56=SUM(ADO56) 
  /ADO57=SUM(ADO57) 
  /ADO58=SUM(ADO58) 
  /ADO59=SUM(ADO59) 
  /ADO60=SUM(ADO60)
  /N_BREAK=N.

DATASET ACTIVATE ADO.

*Create variables for forecast values.
COMPUTE ADO61 = 0.
COMPUTE ADO62 = 0.
COMPUTE ADO63 = 0.
COMPUTE ADO64 = 0.
COMPUTE ADO65 = 0.
COMPUTE ADO66 = 0.
COMPUTE ADO67 = 0.
COMPUTE ADO68 = 0.
COMPUTE ADO69 = 0.
COMPUTE ADO70 = 0.
COMPUTE ADO71 = 0.
COMPUTE ADO72 = 0.
EXE.

FLIP VARIABLES=ADO1 ADO2 ADO3 ADO4 ADO5 ADO6 ADO7 ADO8 ADO9 ADO10 ADO11 ADO12 ADO13 ADO14 ADO15 
    ADO16 ADO17 ADO18 ADO19 ADO20 ADO21 ADO22 ADO23 ADO24 ADO25 ADO26 ADO27 ADO28 ADO29 ADO30 ADO31 
    ADO32 ADO33 ADO34 ADO35 ADO36 ADO37 ADO38 ADO39 ADO40 ADO41 ADO42 ADO43 ADO44 ADO45 ADO46 ADO47 
    ADO48 ADO49 ADO50 ADO51 ADO52 ADO53 ADO54 ADO55 ADO56 ADO57 ADO58 ADO59 ADO60 ADO61 ADO62 ADO63
    ADO64 ADO65 ADO66 ADO67 ADO68 ADO69 ADO70 ADO71 ADO72
  /NEWNAMES=Group.

DATASET NAME DT_TS.
DATASET ACTIVATE DT_TS.

RENAME VARIABLES K_1 = Group1 K_2 = Group2 K_3 = Group3 K_4 = Group4.

DATE M 6 12 Y 2011.

*Group 1 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group1 INDEPENDENT=YEAR_ MONTH_
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 2 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group2
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 3 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group3 INDEPENDENT=YEAR_ MONTH_
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 4 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group4 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

DATASET CLOSE DT_TS.
DATASET CLOSE ADO.

*Aggregate the average daily Gcom orders by group.
DATASET ACTIVATE ACCTS.

DATASET DECLARE AD_GCO.

AGGREGATE
  /OUTFILE='AD_GCO'
  /BREAK=Group
  /ADGCO1=SUM(ADGCO1) 
  /ADGCO2=SUM(ADGCO2) 
  /ADGCO3=SUM(ADGCO3) 
  /ADGCO4=SUM(ADGCO4) 
  /ADGCO5=SUM(ADGCO5) 
  /ADGCO6=SUM(ADGCO6) 
  /ADGCO7=SUM(ADGCO7) 
  /ADGCO8=SUM(ADGCO8) 
  /ADGCO9=SUM(ADGCO9) 
  /ADGCO10=SUM(ADGCO10) 
  /ADGCO11=SUM(ADGCO11) 
  /ADGCO12=SUM(ADGCO12) 
  /ADGCO13=SUM(ADGCO13) 
  /ADGCO14=SUM(ADGCO14) 
  /ADGCO15=SUM(ADGCO15) 
  /ADGCO16=SUM(ADGCO16) 
  /ADGCO17=SUM(ADGCO17) 
  /ADGCO18=SUM(ADGCO18) 
  /ADGCO19=SUM(ADGCO19) 
  /ADGCO20=SUM(ADGCO20) 
  /ADGCO21=SUM(ADGCO21) 
  /ADGCO22=SUM(ADGCO22) 
  /ADGCO23=SUM(ADGCO23) 
  /ADGCO24=SUM(ADGCO24) 
  /ADGCO25=SUM(ADGCO25) 
  /ADGCO26=SUM(ADGCO26) 
  /ADGCO27=SUM(ADGCO27) 
  /ADGCO28=SUM(ADGCO28) 
  /ADGCO29=SUM(ADGCO29) 
  /ADGCO30=SUM(ADGCO30) 
  /ADGCO31=SUM(ADGCO31) 
  /ADGCO32=SUM(ADGCO32) 
  /ADGCO33=SUM(ADGCO33) 
  /ADGCO34=SUM(ADGCO34) 
  /ADGCO35=SUM(ADGCO35) 
  /ADGCO36=SUM(ADGCO36) 
  /ADGCO37=SUM(ADGCO37) 
  /ADGCO38=SUM(ADGCO38) 
  /ADGCO39=SUM(ADGCO39) 
  /ADGCO40=SUM(ADGCO40) 
  /ADGCO41=SUM(ADGCO41) 
  /ADGCO42=SUM(ADGCO42) 
  /ADGCO43=SUM(ADGCO43) 
  /ADGCO44=SUM(ADGCO44) 
  /ADGCO45=SUM(ADGCO45) 
  /ADGCO46=SUM(ADGCO46) 
  /ADGCO47=SUM(ADGCO47) 
  /ADGCO48=SUM(ADGCO48) 
  /ADGCO49=SUM(ADGCO49) 
  /ADGCO50=SUM(ADGCO50) 
  /ADGCO51=SUM(ADGCO51) 
  /ADGCO52=SUM(ADGCO52) 
  /ADGCO53=SUM(ADGCO53) 
  /ADGCO54=SUM(ADGCO54) 
  /ADGCO55=SUM(ADGCO55) 
  /ADGCO56=SUM(ADGCO56) 
  /ADGCO57=SUM(ADGCO57) 
  /ADGCO58=SUM(ADGCO58) 
  /ADGCO59=SUM(ADGCO59) 
  /ADGCO60=SUM(ADGCO60)
  /N_BREAK=N.

DATASET ACTIVATE AD_GCO.

*Create variables for forecast values.
COMPUTE ADGCO61 = 0.
COMPUTE ADGCO62 = 0.
COMPUTE ADGCO63 = 0.
COMPUTE ADGCO64 = 0.
COMPUTE ADGCO65 = 0.
COMPUTE ADGCO66 = 0.
COMPUTE ADGCO67 = 0.
COMPUTE ADGCO68 = 0.
COMPUTE ADGCO69 = 0.
COMPUTE ADGCO70 = 0.
COMPUTE ADGCO71 = 0.
COMPUTE ADGCO72 = 0.
EXE.

FLIP VARIABLES=ADGCO1 ADGCO2 ADGCO3 ADGCO4 ADGCO5 ADGCO6 ADGCO7 ADGCO8 ADGCO9 ADGCO10 ADGCO11 ADGCO12 ADGCO13 ADGCO14 ADGCO15 
    ADGCO16 ADGCO17 ADGCO18 ADGCO19 ADGCO20 ADGCO21 ADGCO22 ADGCO23 ADGCO24 ADGCO25 ADGCO26 ADGCO27 ADGCO28 ADGCO29 ADGCO30 ADGCO31 
    ADGCO32 ADGCO33 ADGCO34 ADGCO35 ADGCO36 ADGCO37 ADGCO38 ADGCO39 ADGCO40 ADGCO41 ADGCO42 ADGCO43 ADGCO44 ADGCO45 ADGCO46 ADGCO47 
    ADGCO48 ADGCO49 ADGCO50 ADGCO51 ADGCO52 ADGCO53 ADGCO54 ADGCO55 ADGCO56 ADGCO57 ADGCO58 ADGCO59 ADGCO60 ADGCO61 ADGCO62 ADGCO63
    ADGCO64 ADGCO65 ADGCO66 ADGCO67 ADGCO68 ADGCO69 ADGCO70 ADGCO71 ADGCO72
  /NEWNAMES=Group.

DATASET NAME DGCO_TS.
DATASET ACTIVATE DGCO_TS.

RENAME VARIABLES K_1 = Group1 K_2 = Group2 K_3 = Group3 K_4 = Group4.

DATE M 6 12 Y 2011.

*Group 1 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group1 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 2 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group2 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 3 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group3 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

*Group 4 Forecast.
USE year 2011 month 6 THRU year 2016 month 5.

PREDICT THRU END.

TSMODEL
   /MODELSUMMARY  PRINT=[MODELFIT]
   /MODELSTATISTICS  DISPLAY=YES MODELFIT=[ SRSQUARE RSQUARE]
   /SERIESPLOT OBSERVED FORECAST FORECASTCI
   /OUTPUTFILTER DISPLAY=ALLMODELS
   /SAVE  PREDICTED(Predicted) LCL(LCL) UCL(UCL) NRESIDUAL(NResidual)
   /AUXILIARY  CILEVEL=90 MAXACFLAGS=24
   /MISSING USERMISSING=EXCLUDE
   /MODEL DEPENDENT=Group4 INDEPENDENT=YEAR_ MONTH_
      PREFIX='Model'
   /EXPERTMODELER TYPE=[ARIMA EXSMOOTH] TRYSEASONAL=YES
   /AUTOOUTLIER  DETECT=OFF.

DATASET CLOSE DGCO_TS.
DATASET CLOSE AD_GCO.

DATASET ACTIVATE ACCTS.

